[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[project]
name = "DipTraceGenerator"
version = "0.1.1"
description = "This is the python library for generating the DipTrace components and patterns libraries."
readme = "README.md"
requires-python = ">=3.8, <4.0"
license = {text = "MIT"}
keywords = ["DipTrace", "PCB"]
authors = [
	{name = "Oleksandr Kolodkin", email = "oleksandr.kolodkin@ukr.net"},
]
maintainers = [
	{name = "Oleksandr Kolodkin", email = "oleksandr.kolodkin@ukr.net"},
]
classifiers = [
	"Development Status :: 2 - Pre-Alpha",
	"Programming Language :: Python :: 3",
	"License :: OSI Approved :: MIT License",
	"Operating System :: OS Independent",
	"Environment :: Console",
	"Intended Audience :: Developers",
	"Natural Language :: English",
	"Topic :: Scientific/Engineering",
	"Topic :: Scientific/Engineering :: Electronic Design Automation (EDA)",
	"Topic :: Software Development :: Libraries",
	"Topic :: Software Development :: Libraries :: Python Modules",
]
dependencies = [
	"lxml>=6.0.0",
	"typing-extensions>=4.11.0; python_version<'3.11'",
	"pillow>=10.0.0,<11.0.0; python_version<'3.9'",
	"pillow>=11.0.0; python_version>='3.9'",
]

[dependency-groups]
dev = [
	"pytest>=8.1.1",
	"pytest-cov>=5.0.0",
]
examples = [
	"tqdm>=4.66.2",
	"colorama>=0.4.6",
]

[project.scripts]
examples = "Examples.all:main"

[project.urls]
Homepage = "https://github.com/kolod/DipTrace-Generator"
Repository = "https://github.com/kolod/DipTrace-Generator"

[tool.poetry.scripts]
examples = "Examples.all:main"

[tool.coverage.report]
exclude_also = [
	"if __name__ == .__main__.:"
]
