name: CI

on:
  push:
    branches:
      - main
      - ai
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:

  test:
    name: Python ${{ matrix.python-version }} tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12', '3.13', '3.14']
      max-parallel: 1
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python3 -

      - name: Check Poetry version
        run: poetry --version

      - name: Upload Poetry installation error log
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: poetry-installer-error-${{ matrix.python-version }}
          path: poetry-installer-error-*.log

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Download coverage data from previous runs
        uses: actions/download-artifact@v4
        if: matrix.python-version != '3.8'
        continue-on-error: true
        with:
          name: coverage-data
          path: .

      - name: Run unit-tests
        if: matrix.python-version == '3.8'
        run: poetry run pytest --cov=DipTraceGenerator --cov-report=term

      - name: Run unit-tests
        if: matrix.python-version != '3.8'
        run: poetry run pytest --cov=DipTraceGenerator --cov-append --cov-report=term

      - name: Upload coverage data for next runs
        uses: actions/upload-artifact@v4
        with:
          name: coverage-data
          path: .coverage
          if-no-files-found: error
          include-hidden-files: true
          overwrite: true

      - name: Upload all if failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-failure-logs-${{ matrix.python-version }}
          path: .
          if-no-files-found: warn

      - name: Generate coverage report and upload to Codecov
        if: matrix.python-version == '3.14'
        run: poetry run coverage xml

      - name: Upload coverage reports to Codecov
        if: matrix.python-version == '3.14'
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          flags: unittests
          files: ./coverage.xml

